meta <- data.frame(
    SourceUrl='https://b2b.hci.utah.edu/gnomex/gnomexGuestFlex.jsp?topicNumber=27',
    SourceType=c('BAM', 'bai', 'BAM', 'bai'),
    SourceVersion=NA,
    SourceLastModifiedDate = as.POSIXct('2018-08-30'),
    SourceMd5=c('82b22b3c546aa1a411b0cbcf07d166e2',
                '5568fd22fbd0fbb4906a384c0331d694',
                '68f175b56f67dd05373cc548c3e37694',
                'f107f186f7b4954e797274be0067d8b6'),
    SourceSize=c(52161549,
                 76360,
                 61592148,
                 75488),
    DataProvider='Bench to Bassinet GnomEx CvDC',
    Title=c('zy13mut',
            'zy13mutIdx',
            'zy13wt',
            'zy13wtIdx'),
    Description=paste('The zy13 mutation was identified and mapped as described',
                      'in Hill et al. in Genome Research (2013). The .fastq',
                      'files for the two pools were downloaded from the B2B',
                      'Consortium\'s GNomEx datahub',
                      'and were aligned to the GRCz11 genome using HISAT2.',
                      'See scripts/make-data.sh for details.',
                      'Abbreviations: wt=wild-type pool, mut=mutant pool,',
                      'Idx=BAM index.'),
    Species='Danio rerio',
    TaxonomyId=7955,
    Genome='GRCz11',
    RDataClass='character',
    RDataPath=c('MMAPPR2data/zy13_mut.bam',
                'MMAPPR2data/zy13_mut.bam.bai',
                'MMAPPR2data/zy13_wt.bam',
                'MMAPPR2data/zy13_wt.bam.bai'),
    Maintainer='Jonathon Hill jhill@byu.edu',
    BiocVersion='3.7',
    Coordinate_1_based=TRUE,
    DispatchClass='FilePath'
)
write.csv(meta, file='inst/extdata/metadata.csv', row.names=FALSE)